site_name: Student Manager Documentation
site_url: https://www.studentmanager.co.za
repo_url: https://github.com/AgileSystemsTechnology/StudentManager.Docs
site_favicon: favicon.ico

pages:
- Home: index.md
   
- People:
    - Adding People - Staff: People/adding-people.md
    - Finding People: People/finding-people.md
    - Bulk Activation Link: People/bulkactivationlinks.md
    - User Profile Details Update Request: People/userprofileupdatescreate.md

- Modules:
    - Add a Module: Modules/addamodule.md
    - Moving Modules: Modules/movingmodules.md
    - Setting up Module Groups: Modules/settingupmodulegroups.md
    - Setting up Assessments: Modules/settingupassessments.md
    - Assessment Attempts: Modules/assessmentattempts.md
    - Copy Assessments in Bulk: Modules/copyassessmentsinbulk.md
    - Online Tests: Modules/onlinetests.md
    - Online Assessment: Modules/onlineassessments.md
    - Grade Assessments: Modules/grading.md
    - Adding E-Learning Material: Modules/addinglearningmaterial.md 
    - Merging Duplicate Modules: Modules/mergingduplicatemodules.md
    - Setting Up Assessments: Modules/settingupassessments.md

- Qualifications:
    - Add a Qualification: Qualifications/addaqualification.md

- Reports:
    - Print a Lecture Time Table: Reports/printalecturetimetable.md
    - Print a Student Card: Reports/printingastudentcard.md
    - Printing Academic Transcripts: Reports/printingacademictranscripts.md

- Calendar:
    - Create Events: Calendar/createevents.md 

- Leads:
    - Navigation: Leads/leadsnavigation.md

- Applicants:
    - Adding an Applicant: Applications/addinganapplicant.md
        
- Communication:
    - Creating an Inbox: Communication/settingsupaninbox.md
    - Sending an SMS: Communication/sendingansms.md

- Moodle:
    - Moodle Integration: Moodle/moodleintegration.md


- More:
    - Creating and Moving Logs: More/creatingormovinglogs.md
    - Grade and Symbol Settings: More/gradeandsymbolsettings.md

    
theme: readthedocs
