site_name: Student Manager Documentation
site_url: https://www.studentmanager.co.za
repo_url: https://github.com/AgileSystemsTechnology/StudentManager.Docs
site_favicon: favicon.ico

pages:
- Welcome: index.md

- Login:
    - System Login: Login/loginpasswordreset.md
    
- Home:
    - Noticeboard: Home/homenoticeboard.md

- People:
    - Finding People: People/finding-people.md
    - User Account Activation: People/activationlinks.md
    
- People - User:
    - Finding People: People/finding-people.md
    - User Account Activation: People/activationlinks.md
    
- People - Employee:
    - Finding People: People/finding-people.md
    - User Account Activation: People/activationlinks.md

- People - Student:
    - Finding People: People/finding-people.md
    - User Account Activation: People/activationlinks.md

- People - Applicant:
    - Finding People: People/finding-people.md
    - User Account Activation: People/activationlinks.md
    
- People - Lead:
    - Finding People: People/finding-people.md
    - User Account Activation: People/activationlinks.md

theme: readthedocs
