site_name: Student Manager Documentation
site_url: https://www.studentmanager.co.za
repo_url: https://github.com/AgileSystemsTechnology/StudentManager.Docs
site_favicon: favicon.ico

pages:
- Welcome: index.md

- Login:
    - Password Reset: Login/loginpasswordreset.md
    
- Home:
    - Noticeboard: Home/homenoticeboard.md
   

theme: readthedocs
